### ISSUE TITLE
setup.py depends on pathlib

### ISSUE THREAD

**Issue by unipolar** [cloudblue/connect-python-sdk#106]
not critical, but it complicates installation process.

```
# virtualenv venv
New python executable in /root/venv/bin/python
Installing setuptools, pip, wheel...done.
# . venv/bin/activate
# pip install connect-sdk
Collecting connect-sdk
  Downloading https://files.pythonhosted.org/packages/d7/0e/5b3f6cbd75e6418bcbd20f2e3a6472c5f22916989b82fe6c68c3e59fd812/connect-sdk-19.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7rYWJp/connect-sdk/setup.py", line 10, in <module>
        import pathlib
    ImportError: No module named pathlib
```

it also doesn't help when we explicitly specify pathlib in our requirements.txt

```
# cat requirements.txt 
pathlib
connect-sdk
# pip install -r requirements.txt 
Collecting pathlib (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 561kB/s 
Collecting connect-sdk (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d7/0e/5b3f6cbd75e6418bcbd20f2e3a6472c5f22916989b82fe6c68c3e59fd812/connect-sdk-19.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-msYv45/connect-sdk/setup.py", line 10, in <module>
        import pathlib
    ImportError: No module named pathlib
```

**Comment by marcserrat** [comment]
Hi

i found out that i can reproduce only this with pip 20.0.1 that caused multiple problems. As you may know PIP changed internals and some ways to detect requirements are not working anymore. If you are using pip 20.0.2 or 19 it works properly

**Comment by unipolar** [comment]
python:2 docker with pip 20.0.2
```
| => sudo docker run -it python:2 pip install connect-sdk
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting connect-sdk
  Downloading connect-sdk-19.3.tar.gz (37 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zzJTXd/connect-sdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zzJTXd/connect-sdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-zzJTXd/connect-sdk/pip-egg-info
         cwd: /tmp/pip-install-zzJTXd/connect-sdk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zzJTXd/connect-sdk/setup.py", line 10, in <module>
        import pathlib
    ImportError: No module named pathlib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

python:2 docker with pip upgraded to latest
```
#docker run -it python:2 /bin/bash -c "pip install -U pip && pip install connect-sdk"
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Pytho
n 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pip
  Downloading pip-20.1.1-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 803 kB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.1.1
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in Januar
y 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting connect-sdk
  Downloading connect-sdk-19.3.tar.gz (37 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Lm9rjr/connect-sdk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Lm9rjr/connect-s
dk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --eg
g-base /tmp/pip-pip-egg-info-tq7jSQ
         cwd: /tmp/pip-install-Lm9rjr/connect-sdk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Lm9rjr/connect-sdk/setup.py", line 10, in <module>
        import pathlib
    ImportError: No module named pathlib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

as I can see starting from python3.4 pathlib is builtin.

So no, pip upgrade doesn't help. But the issue is only valid for python2.7
