### ISSUE TITLE
constraints.Constraints is not JSON serializable exception in InquireRequest and update_parameters

### ISSUE THREAD

**Issue by unipolar** [cloudblue/connect-python-sdk#111]
after update to v19.3 this example doesn't work because param contains constraints.Constraints object.
```
class FulfillmentTest(FulfillmentAutomation):
    def process_request(self, request):
             username_ error = True
             for param in request.asset.params:
                    if param.name == 'user' and username_error:
                        param.value_error = 'This user name is already taken, please choose a different name'
                        raise InquireRequest(params=[param])
```
 
same exception in
```
         p = request.asset.params[p]
         p.value = 'value'
         self.update_parameters(request.id, [p])
```

example log/backtrace:
```
 DEBUG ; 2020-07-09 10:22:15,270; root  ; logger:wrapper:line-34: Function params: () {'path': u'PR-3168-4931-4525-001', 'json': {'asset': {'params': [{'description': u'Project admin username', 'name': u'user', 'title': u'User', 'value': u'admin1', 'value_error': 'This user name is already taken, please choose a different name', 'type': u'text', 'id': u'user', 'constraints': <connect.models.constraints.Constraints object at 0x7fa190d8fbd0>}]}}}
Traceback (most recent call last):
  File "/usr/bin/cloudblue-fulfillments", line 7, in <module>
    rv = connector.process_fulfillment()
  File "/usr/lib/python2.7/site-packages/cloudblue_connector/__init__.py", line 1154, in process_fulfillment
    manager.process()
  File "/usr/lib/python2.7/site-packages/connect_sdk-v19.3-py2.7.egg/connect/logger/logger.py", line 35, in wrapper
    result = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/connect_sdk-v19.3-py2.7.egg/connect/resources/automation_engine.py", line 31, in process
    self.dispatch(request)
  File "/usr/lib/python2.7/site-packages/connect_sdk-v19.3-py2.7.egg/connect/logger/logger.py", line 35, in wrapper
    result = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/connect_sdk-v19.3-py2.7.egg/connect/resources/fulfillment_automation.py", line 111, in dispatch
    self.update_parameters(request.id, inquire.params)
  File "/usr/lib/python2.7/site-packages/connect_sdk-v19.3-py2.7.egg/connect/logger/logger.py", line 35, in wrapper
    result = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/connect_sdk-v19.3-py2.7.egg/connect/resources/fulfillment_automation.py", line 187, in update_parameters
    json={'asset': {'params': list_dict}},
  File "/usr/lib/python2.7/site-packages/connect_sdk-v19.3-py2.7.egg/connect/logger/logger.py", line 35, in wrapper
    result = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/connect_sdk-v19.3-py2.7.egg/connect/resources/base.py", line 83, in put
    response = requests.put(**kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 131, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 466, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 380, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 291, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 373, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 268, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <connect.models.constraints.Constraints object at 0x7fa190d8fb50> is not JSON serializable
```

**Comment by marcserrat** [comment]
Please use python openapi client instead.

is available at: github.com/cloudblue/connect-python-openapi-client
