### ISSUE TITLE
connect-sdk installation fails with python 2.7

### ISSUE THREAD

**Issue by DmitryBondDmitry** [cloudblue/connect-python-sdk#123]
Python version: 2.7.5
pip version: 8.1.2-6
Requests version: 2.25.1
Marshmallow version: 3.10.0

During the installation of connect-sdk following issue encountered:

`pip install connect-sdk
Collecting connect-sdk
  Using cached https://files.pythonhosted.org/packages/2e/ea/4b50ad11337846c0bf52b4d62275253d88de74ab6508601953de73a69c66/connect-sdk-21.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6nO1zc/connect-sdk/setup.py", line 59, in <module>
        'Operating System :: Unix',
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup
        run_setup(setup_script, args)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 69, in run_setup
        lambda: execfile(
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 120, in run
        return func()
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 71, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 21, in <module>
        PACKAGES = find_packages(exclude=['tests*'])
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/opt/rh/python27/root/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/easy_install-4vciEa/pytest-runner-5.2/setuptools_scm-5.0.1-py2.7.egg/setuptools_scm/integration.py", line 9, in version_keyword
      File "/tmp/easy_install-4vciEa/pytest-runner-5.2/setuptools_scm-5.0.1-py2.7.egg/setuptools_scm/version.py", line 62, in _warn_if_setuptools_outdated
    setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)`

But setuptools upgrade failed with:
`python -m pip install --upgrade setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/12/68/95515eaff788370246dac534830ea9ccb0758e921ac9e9041996026ecaf2/setuptools-53.0.0.tar.gz (2.1MB)
    100% |████████████████████████████████| 2.1MB 496kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setuptools/__init__.py", line 16, in <module>
        import setuptools.version
      File "setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "pkg_resources/__init__.py", line 1367
        raise SyntaxError(e) from e
                                ^
    SyntaxError: invalid syntax`

Could you please advise on which dependent packages require for connect-sdk installation?
Is it still possible to use python 2.7?

**Comment by marcserrat** [comment]
HI,

looks to me that issue is old pip and setuptools. Please try to update them.

I also have 2 suggestions for you:

a) Please do not use old python that is EOL, even that keeps supported on our side to not brake backwards compatibility, for new deployments makes sense to use supported versions.
b) If your plan is to create a new integration, i will suggest you to use the connect-openapi-client instead of the SDK, is way more powerful, flexible and gives access to everything.
